"""ADR-0012 Host 控制层。

当前 expand 阶段暴露逐步 Agent Session 协议、单 Candidate Analysis tracer
(Claim/假设门槛与案卷冻结)、Recon→Candidate Store 入口、Candidate 去重/
评分/双队列、独立 Verification(案卷队列、Claim Result、verdict 聚合与
Finding)与运行级预算(协议重生成×3、轮次/请求/工具/活动时长台账、四层
配置解析与生效快照);票 11 起增加运行世代(manifest/run_state)、工作区
活动锁与串行运行驱动(单一有效配置下发、共享 RunBudget、Recon 恢复、
Related 幂等回队、not_started 收账);票 12 起增加确定性 severity 矩阵、
固定顺序事实报告、完成门与运行封存(report digest + manifest seal +
completed,finalizing 可恢复),票 13 增加封存结果上的追加式 review
overlay;公开入口切换由后续工单继续内聚在本包。
"""

from .analysis import (
    DEFAULT_ANALYSIS_MAX_ROUNDS,
    Candidate,
    HostAnalysisTracer,
    Investigation,
    ProposalRejectedError,
    resolve_analysis_max_rounds,
)
from .budget import (
    BUDGET_SCHEMA_VERSION,
    CONFIG_SCHEMA_VERSION,
    DEFAULT_BUDGET_CONFIG,
    ENV_KEYS,
    BudgetExhaustedError,
    BudgetLedger,
    ConfigError,
    RunBudget,
    load_config_snapshot,
    persist_config_snapshot,
    resolve_effective_config,
)
from .driver import RunDriver, RunSummary
from .generation import (
    MANIFEST_SCHEMA_VERSION,
    RUN_STATE_SCHEMA_VERSION,
    create_generation,
    list_generations,
    load_run_state,
    read_manifest,
    save_run_state,
)
from .locking import LockActiveError, acquire_lock
from .reporting import (
    ANALYST_NOTES_HEADING,
    SealError,
    build_evidence_index,
    build_fact_report,
    completion_gate,
    seal_run,
)
from .review import (
    REVIEW_PROJECTION_SCHEMA_VERSION,
    REVIEW_SCHEMA_VERSION,
    ReviewError,
    ReviewOverlay,
    SEVERITY_LEVELS,
    load_review_projection,
    project_review_report,
)
from .candidates import (
    CANDIDATE_STORE_SCHEMA_VERSION,
    CLAIM_PROFILES,
    RELATED_CANDIDATE_FIELDS,
    CandidateIntakeError,
    CandidateStore,
    ComparisonOutcome,
    IntakeCandidate,
    PriorityScorer,
    RelatedOrigin,
    Selection,
    SemanticComparator,
    coverage_fingerprint,
    normalize_intake,
    normalize_target_path,
    related_candidate_contract,
    related_candidate_records,
    related_intake,
    select_for_processing,
    signal_fingerprint,
    stored_related_proposals,
)
from .claims import (
    ADMISSION_REASONS,
    CASE_SCHEMA_VERSION,
    CLAIM_STATUSES,
    DISPOSITIONS,
    LIFECYCLE_STATUSES,
    STOP_REASONS,
    GateResult,
    PolicyError,
    action_progressed,
    assert_lifecycle_transition,
    assert_terminal,
    build_case_payload,
    evaluate_ready_gate,
    is_decisive,
    profile_claim_document,
    required_claims,
)
from .evidence import EvidenceReference
from .recon import (
    CandidateProposal,
    HostReconRunner,
    ReconRunResult,
    build_site_overview,
    input_failure_reason,
)
from .severity import (
    CLAIM_RESULT_FACETS,
    IMPACT_SCOPES,
    MITIGATION_EFFECTS,
    SEVERITY_LEVELS,
    SEVERITY_MATRIX,
    TRIGGER_CONDITIONS,
    severity_assessment,
)
from .session import (
    MAX_PROTOCOL_ATTEMPTS,
    ActionProposal,
    AgentSession,
    FinalProposal,
    ProposalError,
    ValidationIssue,
    parse_proposal,
    protocol_instruction,
    revalidate_proposal,
)
from .verification import (
    CLAIM_RESULT_JUDGMENTS,
    DEFAULT_VERIFICATION_MAX_ROUNDS,
    FINDING_SCHEMA_VERSION,
    RESULTS_SCHEMA_VERSION,
    VERDICTS,
    CaseOutcome,
    HostVerificationRunner,
    VerificationDeltaPlan,
    VerdictResult,
    aggregate_verdict,
    apply_verification_delta_plan,
    build_case_brief,
    build_finding_payload,
    load_cases,
    load_findings_document,
    plan_verification_queue,
    resolve_verification_max_rounds,
    validate_verification_delta,
)

__all__ = [
    "acquire_lock",
    "action_progressed",
    "ActionProposal",
    "ADMISSION_REASONS",
    "AgentSession",
    "aggregate_verdict",
    "ANALYST_NOTES_HEADING",
    "apply_verification_delta_plan",
    "assert_lifecycle_transition",
    "assert_terminal",
    "BUDGET_SCHEMA_VERSION",
    "BudgetExhaustedError",
    "BudgetLedger",
    "build_case_brief",
    "build_case_payload",
    "build_evidence_index",
    "build_fact_report",
    "build_finding_payload",
    "build_site_overview",
    "Candidate",
    "CANDIDATE_STORE_SCHEMA_VERSION",
    "CandidateIntakeError",
    "CandidateProposal",
    "CandidateStore",
    "CASE_SCHEMA_VERSION",
    "CaseOutcome",
    "CLAIM_PROFILES",
    "CLAIM_RESULT_FACETS",
    "CLAIM_RESULT_JUDGMENTS",
    "CLAIM_STATUSES",
    "ComparisonOutcome",
    "completion_gate",
    "CONFIG_SCHEMA_VERSION",
    "ConfigError",
    "coverage_fingerprint",
    "create_generation",
    "DEFAULT_ANALYSIS_MAX_ROUNDS",
    "DEFAULT_BUDGET_CONFIG",
    "DEFAULT_VERIFICATION_MAX_ROUNDS",
    "DISPOSITIONS",
    "ENV_KEYS",
    "evaluate_ready_gate",
    "EvidenceReference",
    "FinalProposal",
    "FINDING_SCHEMA_VERSION",
    "GateResult",
    "HostAnalysisTracer",
    "HostReconRunner",
    "HostVerificationRunner",
    "IMPACT_SCOPES",
    "input_failure_reason",
    "IntakeCandidate",
    "Investigation",
    "is_decisive",
    "LIFECYCLE_STATUSES",
    "list_generations",
    "load_cases",
    "load_config_snapshot",
    "load_findings_document",
    "load_review_projection",
    "load_run_state",
    "LockActiveError",
    "MANIFEST_SCHEMA_VERSION",
    "MAX_PROTOCOL_ATTEMPTS",
    "MITIGATION_EFFECTS",
    "normalize_intake",
    "normalize_target_path",
    "parse_proposal",
    "persist_config_snapshot",
    "plan_verification_queue",
    "PolicyError",
    "PriorityScorer",
    "profile_claim_document",
    "project_review_report",
    "ProposalError",
    "ProposalRejectedError",
    "protocol_instruction",
    "read_manifest",
    "ReconRunResult",
    "related_candidate_contract",
    "RELATED_CANDIDATE_FIELDS",
    "related_candidate_records",
    "related_intake",
    "RelatedOrigin",
    "required_claims",
    "resolve_analysis_max_rounds",
    "resolve_effective_config",
    "resolve_verification_max_rounds",
    "RESULTS_SCHEMA_VERSION",
    "revalidate_proposal",
    "REVIEW_PROJECTION_SCHEMA_VERSION",
    "REVIEW_SCHEMA_VERSION",
    "ReviewError",
    "ReviewOverlay",
    "RUN_STATE_SCHEMA_VERSION",
    "RunBudget",
    "RunDriver",
    "RunSummary",
    "save_run_state",
    "seal_run",
    "SealError",
    "select_for_processing",
    "Selection",
    "SemanticComparator",
    "severity_assessment",
    "SEVERITY_LEVELS",
    "SEVERITY_MATRIX",
    "signal_fingerprint",
    "STOP_REASONS",
    "stored_related_proposals",
    "validate_verification_delta",
    "ValidationIssue",
    "VerdictResult",
    "VERDICTS",
    "VerificationDeltaPlan",
]
